### ISSUE TITLE
Skeleton's missing dependencies

### ISSUE THREAD

**Issue by diegonc** [apollostack/saturn#43]
Skeleton is missing following dependencies:

* graphql-tools
* react-redux

You have to install them for `npm run dev` to work.

**Comment by rdrey** [comment]
I opened https://github.com/apollostack/saturn/pull/39 for graphql-tools. I don't remember having had issues with react-redux, but that might have changed by now

**Comment by diegonc** [comment]
Oh, thanks, I didn't noticed the pull request. About react-redux, I'm getting the following error:

```
[piping] can't execute file: /home/diego/develop/saturn-app/node_modules/saturn-framework/bin/saturn.js
[0] [piping] error given was: Error: Cannot find module 'react-redux'
[0]     at Function.Module._resolveFilename (module.js:325:15)
[0]     at Function._module2.default._resolveFilename (/home/diego/develop/saturn-app/node_modules/saturn-framework/node_modules/webpack-isomorphic-tools/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:423:34)
[0]     at Function.module._load (/home/diego/develop/saturn-app/node_modules/saturn-framework/node_modules/piping/lib/launcher.js:24:23)
[0]     at Module.require (module.js:353:17)
[0]     at require (internal/module.js:12:17)
[0]     at Object.<anonymous> (/home/diego/develop/saturn-app/ui/components/Hello.js:2:1)
...
```

Maybe the UI didn't use redux before.
